### PR TITLE
Fixed a funny typo

### PR DESCRIPTION
**Pull request by jhorsman**

### CODE REVIEW

**Comment by rpannekoek** [comment]
Almost too funny to fix! :-)

**Comment by azarakovsky** [comment]
ServerError.jsp was moved out of modules, so this PR is now not ready to merge. Fixed anyway at a new place.

**Comment by jhorsman** [comment]
Where did the error.jsp move to?

**Comment by rpannekoek** [comment]
We're improving the separation between DXA Framework, Core Module and Web App in DXA 1.6.  As part of that, the error views are moving to the Web App (to make it easier to customize them).

**Pull request closed without merging**
